// Code generated by MockGen. DO NOT EDIT.
// Source: note.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	dto "github.com/lzimin05/course-todo/internal/transport/dto/note"
)

// MockINoteUsecase is a mock of INoteUsecase interface.
type MockINoteUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockINoteUsecaseMockRecorder
}

// MockINoteUsecaseMockRecorder is the mock recorder for MockINoteUsecase.
type MockINoteUsecaseMockRecorder struct {
	mock *MockINoteUsecase
}

// NewMockINoteUsecase creates a new mock instance.
func NewMockINoteUsecase(ctrl *gomock.Controller) *MockINoteUsecase {
	mock := &MockINoteUsecase{ctrl: ctrl}
	mock.recorder = &MockINoteUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINoteUsecase) EXPECT() *MockINoteUsecaseMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockINoteUsecase) CreateNote(ctx context.Context, req dto.CreateOrUpdateNote) (*dto.CreateNoteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, req)
	ret0, _ := ret[0].(*dto.CreateNoteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockINoteUsecaseMockRecorder) CreateNote(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockINoteUsecase)(nil).CreateNote), ctx, req)
}

// DeleteNote mocks base method.
func (m *MockINoteUsecase) DeleteNote(ctx context.Context, noteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockINoteUsecaseMockRecorder) DeleteNote(ctx, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockINoteUsecase)(nil).DeleteNote), ctx, noteID)
}

// GetAllNotes mocks base method.
func (m *MockINoteUsecase) GetAllNotes(ctx context.Context) ([]*dto.NoteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotes", ctx)
	ret0, _ := ret[0].([]*dto.NoteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotes indicates an expected call of GetAllNotes.
func (mr *MockINoteUsecaseMockRecorder) GetAllNotes(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotes", reflect.TypeOf((*MockINoteUsecase)(nil).GetAllNotes), ctx)
}

// GetNotesByProject mocks base method.
func (m *MockINoteUsecase) GetNotesByProject(ctx context.Context, projectID uuid.UUID) ([]*dto.NoteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesByProject", ctx, projectID)
	ret0, _ := ret[0].([]*dto.NoteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesByProject indicates an expected call of GetNotesByProject.
func (mr *MockINoteUsecaseMockRecorder) GetNotesByProject(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesByProject", reflect.TypeOf((*MockINoteUsecase)(nil).GetNotesByProject), ctx, projectID)
}

// UpdateNote mocks base method.
func (m *MockINoteUsecase) UpdateNote(ctx context.Context, noteID uuid.UUID, req dto.CreateOrUpdateNote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockINoteUsecaseMockRecorder) UpdateNote(ctx, noteID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockINoteUsecase)(nil).UpdateNote), ctx, noteID, req)
}
