// Code generated by MockGen. DO NOT EDIT.
// Source: note.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	models "github.com/lzimin05/course-todo/internal/models/note"
)

// MockINoteRepository is a mock of INoteRepository interface.
type MockINoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockINoteRepositoryMockRecorder
}

// MockINoteRepositoryMockRecorder is the mock recorder for MockINoteRepository.
type MockINoteRepositoryMockRecorder struct {
	mock *MockINoteRepository
}

// NewMockINoteRepository creates a new mock instance.
func NewMockINoteRepository(ctrl *gomock.Controller) *MockINoteRepository {
	mock := &MockINoteRepository{ctrl: ctrl}
	mock.recorder = &MockINoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINoteRepository) EXPECT() *MockINoteRepositoryMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockINoteRepository) CreateNote(ctx context.Context, projectID, userID uuid.UUID, name, description string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, projectID, userID, name, description)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockINoteRepositoryMockRecorder) CreateNote(ctx, projectID, userID, name, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockINoteRepository)(nil).CreateNote), ctx, projectID, userID, name, description)
}

// DeleteNote mocks base method.
func (m *MockINoteRepository) DeleteNote(ctx context.Context, userID, noteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, userID, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockINoteRepositoryMockRecorder) DeleteNote(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockINoteRepository)(nil).DeleteNote), ctx, userID, noteID)
}

// GetAllNotes mocks base method.
func (m *MockINoteRepository) GetAllNotes(ctx context.Context, userID uuid.UUID) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotes", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotes indicates an expected call of GetAllNotes.
func (mr *MockINoteRepositoryMockRecorder) GetAllNotes(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotes", reflect.TypeOf((*MockINoteRepository)(nil).GetAllNotes), ctx, userID)
}

// GetNotesByProject mocks base method.
func (m *MockINoteRepository) GetNotesByProject(ctx context.Context, projectID, userID uuid.UUID) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesByProject", ctx, projectID, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesByProject indicates an expected call of GetNotesByProject.
func (mr *MockINoteRepositoryMockRecorder) GetNotesByProject(ctx, projectID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesByProject", reflect.TypeOf((*MockINoteRepository)(nil).GetNotesByProject), ctx, projectID, userID)
}

// UpdateNote mocks base method.
func (m *MockINoteRepository) UpdateNote(ctx context.Context, userID, noteID, projectID uuid.UUID, name, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, userID, noteID, projectID, name, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockINoteRepositoryMockRecorder) UpdateNote(ctx, userID, noteID, projectID, name, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockINoteRepository)(nil).UpdateNote), ctx, userID, noteID, projectID, name, description)
}

// MockNoteProjectRepository is a mock of NoteProjectRepository interface.
type MockNoteProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNoteProjectRepositoryMockRecorder
}

// MockNoteProjectRepositoryMockRecorder is the mock recorder for MockNoteProjectRepository.
type MockNoteProjectRepositoryMockRecorder struct {
	mock *MockNoteProjectRepository
}

// NewMockNoteProjectRepository creates a new mock instance.
func NewMockNoteProjectRepository(ctrl *gomock.Controller) *MockNoteProjectRepository {
	mock := &MockNoteProjectRepository{ctrl: ctrl}
	mock.recorder = &MockNoteProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteProjectRepository) EXPECT() *MockNoteProjectRepositoryMockRecorder {
	return m.recorder
}

// CheckProjectAccess mocks base method.
func (m *MockNoteProjectRepository) CheckProjectAccess(ctx context.Context, projectID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProjectAccess", ctx, projectID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProjectAccess indicates an expected call of CheckProjectAccess.
func (mr *MockNoteProjectRepositoryMockRecorder) CheckProjectAccess(ctx, projectID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProjectAccess", reflect.TypeOf((*MockNoteProjectRepository)(nil).CheckProjectAccess), ctx, projectID, userID)
}
